name: tests

on:
  push:         {branches: [cl]}
  pull_request: {branches: [cl]}

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        imgtag:
          - "golang:1.19.1-buster"
        goarch:
          - "amd64"
        nsq_ver:
          - "https://github.com/cloudlinux/nsq/releases/download/1.2.1-1/nsq-1.2.1-1.linux-amd64.go1.19.1.tar.gz"

    container: "${{matrix.imgtag}}"
    env:
      GOPATH: "${{github.workspace}}/go"
      GOARCH: "${{matrix.goarch}}"
      SRCDIR: "go/src/github.com/nsqio/go-nsq"

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{env.SRCDIR}}

      - name: download NSQ
        run: |
          cd ${{env.SRCDIR}}
          curl -sSL "${{matrix.nsq_ver}}" | tar -xzv --strip-components=1

      - name: test
        run: |
          cd ${{env.SRCDIR}}
          export PATH=bin:$PATH
          ./test.sh
